server:
  port: 9000
  servlet:
    context-path: /collection
spring:
  profiles:
    active: dev
  datasource:
    # 连接池配置
    hikari:
      maximum-pool-size: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-lock-table: KC_CO_DATABASECHANGELOGLOCK
    database-change-log-table: KC_CO_DATABASECHANGELOG
  servlet:
    multipart:
      # 上传文件大小
      max-file-size: 1GB
      #请求总上传大小
      max-request-size: 10GB
  web:
    resources:
      static-locations: classpath:/static/
  jackson:
    default-property-inclusion: non_null
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 100
      thread-name-prefix: thumbnail-task-

#指定mybatis-config.xml的位置
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml
  type-handlers-package: com.keem.kochiu.collection.config
  global-config:
    db-config:
      id-type: auto

collection:
  upload-type:
    image:
      - jpg
      - jpeg
      - gif
      - bmp
      - png
      - webp
      - tif
      - psd
      - psb
      - dng
      - nef
      - cr2
      - arw
    document:
      - pdf
      - txt
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
    video:
      - mp4
      - mov
      - avi
    audio:
      - wav
      - mp3
      - flac
    other:
