server:
  port: 9000
  servlet:
    context-path: /collection
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${user.dir}/db/collection.db
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-lock-table: KC_CO_DATABASECHANGELOGLOCK
    database-change-log-table: KC_CO_DATABASECHANGELOG
  servlet:
    multipart:
      # 上传文件大小
      max-file-size: 10MB
      #请求总上传大小
      max-request-size: 100MB
  jackson:
    default-property-inclusion: non_null

#指定mybatis-config.xml的位置
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml
  type-handlers-package: com.keem.kochiu.collection.config
  global-config:
    db-config:
      id-type: auto

collection:
  upload-type:
    image:
      - jpg
      - jpeg
      - gif
      - bmp
      - png
      - webp
    document:
      - pdf
      - txt
      - doc
      - docx
      - xls
      - xlsx
      - ppt
      - pptx
    video:
      - mp4
      - mov
      - avi
    audio:
      - wav
      - mp3
      - flac
    other:
