server:
  port: 9000
  servlet:
    context-path: /collection
  tomcat:
    max-swallow-size: 5GB  # 必须确保这一行无缩进错误
    connection-timeout: 600000
    max-http-form-post-size: 5GB

spring:
  profiles:
    active: dev
  datasource:
    # 连接池配置
    hikari:
      maximum-pool-size: 1
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    database-change-log-lock-table: KC_CO_DATABASECHANGELOGLOCK
    database-change-log-table: KC_CO_DATABASECHANGELOG
  servlet:
    multipart:
      enabled: true
      # 上传文件大小
      max-file-size: 2GB
      #请求总上传大小
      max-request-size: 10GB
  web:
    resources:
      static-locations: classpath:/static/
  jackson:
    default-property-inclusion: non_null
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 1000  # 增加队列容量
        keep-alive: 120s     # 增加线程保持活动时间
        allow-core-thread-timeout: true
      thread-name-prefix: thumbnail-task-
      shutdown:
        await-termination: true
        await-termination-period: 60s

#指定mybatis-config.xml的位置
mybatis-plus:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:/mapper/*.xml
  type-handlers-package: com.keem.kochiu.collection.config
  global-config:
    db-config:
      id-type: auto
