collection:
  jodconverter:
    enabled: true
    mode: local
    remote:
      username: admin
      password: 123456
      api-host: http://localhost:8080
      timeout: 300000 #单位：毫秒(5分钟)
    local:
      office-home: /Applications/LibreOffice.app/Contents
  ffmpeg:
    enabled: true
    mode: local
    remote:
      api-url: http://localhost:8000/capture
    local:
      ffmpeg-path: /opt/homebrew/Cellar/ffmpeg/7.1.1_1/bin
  graphicsMagick:
    enabled: true
    mode: local
    remote:
      api-url: http://localhost:8000/capture
      timeout: 300000
    local:
      graphics-magick-path: /opt/homebrew/bin
